name: 💎 CI Build & Push Image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_push_appserver:
    name: Build and push Appserver image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Appserver image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/mykidz-appserver.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-appserver:latest

  build_and_push_nginx:
    name: Build and push Nginx image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Nginx image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/mykidz-nginx.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-nginx:latest

  build_and_push_postgres:
    name: Build and push Postgres image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Postgres image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/mykidz-postgres.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-postgres:latest

  build_and_push_redis:
    name: Build and push Redis image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Redis image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/mykidz-redis.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-redis:latest

  build_and_push_pgadmin4:
    name: Build and push PGAdmin4 image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push PGAdmin4 image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/mykidz-pgadmin4.Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-pgadmin4:latest

  push_compose_file_to_s3:
    runs-on: ubuntu-latest
    needs:
      - build_and_push_appserver
      - build_and_push_nginx
      - build_and_push_postgres
      - build_and_push_redis
      - build_and_push_pgadmin4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp docker-compose.yaml s3://${{secrets.S3_BUCKET_NAME}}/
