name: 💎 CI Build & Push Image

on:
  push:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    needs: ci-lint
    outputs:
      should_skip: ${{ needs.ci-lint.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths: '["src/**", "libs/**", "apps/**", "test/**"]'
          do_not_skip: '["workflow_dispatch", "schedule"]'

  build_and_push_appserver:
    name: Build and push Appserver image
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Appserver image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/
          dockerfile: Dockerfile.mykidz-appserver
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-appserver:latest

  build_and_push_nginx:
    name: Build and push Nginx image
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Nginx image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/
          dockerfile: Dockerfile.mykidz-nginx
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-nginx:latest

  build_and_push_postgres:
    name: Build and push Postgres image
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Postgres image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/
          dockerfile: Dockerfile.mykidz-postgres
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-postgres:latest

  build_and_push_redis:
    name: Build and push Redis image
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Redis image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/
          dockerfile: Dockerfile.mykidz-redis
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-redis:latest

  build_and_push_pgadmin4:
    name: Build and push PGAdmin4 image
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push PGAdmin4 image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/
          dockerfile: Dockerfile.mykidz-pgadmin4
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-pgadmin4:latest
