name: 💎 CI Build & Push Image

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: appserver
            dockerfile: Dockerfile.mykidz-appserver
          - name: nginx
            dockerfile: Dockerfile.mykidz-nginx
          - name: postgres
            dockerfile: Dockerfile.mykidz-postgres
          - name: redis
            dockerfile: Dockerfile.mykidz-redis
          - name: pgadmin4
            dockerfile: Dockerfile.mykidz-pgadmin4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push ${{ matrix.image }} image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/
          dockerfile: ${{ matrix.dockerfile }}
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mykidz-${{ matrix.image }}:latest
