name: PR Role Enforcement

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  pull_request_review:
    types:
      - submitted

jobs:
  check-role:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check if only reviewers can approve
      if: github.event_name == 'pull_request_review'
      run: |
        reviewer=$(jq -r ".review.user.login" "$GITHUB_EVENT_PATH")
        
        if [[ ! " $reviewers " =~ " $reviewer " ]]; then
          echo "::error::Only reviewers can approve the PR."
          exit 1
        fi

    - name: Check if only reviewers can merge
      if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
      run: |
        reviewer=$(jq -r ".review.user.login" "$GITHUB_EVENT_PATH")
        
        if [[ ! " $reviewers " =~ " $reviewer " ]]; then
          echo "::error::Only reviewers can merge the PR."
          exit 1
        fi
